
world_pause;

interact_with_npc INTERACTION_LOOK, ENTITY_ID_PLAYER, ENTITY_ID_SUBJECT;
cam_look_npc ENTITY_ID_SUBJECT;

if not has_repaired_health_machine then
    say "This machine has nanites. Transporting them will be time sensitive.";
    ask "Take some?";

    if ask_response() then
        has_health_juice = true;
        cancel_timer;
        start_timer 120, "rom:/scripts/health_juice_expire.script";
    end
else
    say "You no longer need nanites.";
end

world_unpause;
cam_return;